[project]
name = "langgraph-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "langchain[anthropic]>=0.3.27",
    "langgraph>=0.6.2",
    "python-dotenv>=1.1.1",
]
